name: Upload Nightly
description: A GitHub Action to upload artifacts nightly
author: Your Name
version: 1.0.0

inputs:
  artifacts_path:
    description: 'Path to the artifacts directory'
    required: true
  anaconda_nightly_upload_token:
    description: 'Token to upload to scientific python org'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
